; *****************************************************************************
; *****************************************************************************
;
;		Name:		assembler.inc
;		Author:		Paul Robson (paul@robsons.org.uk)
;		Date:		17 Dec 2020
;		Purpose:	Addressing Modes.
;
; *****************************************************************************
; *****************************************************************************

AM_Immediate = 0
AM_Zero = 1
AM_Implied = 2
AM_Abs = 3
AM_ZeroIndY = 4
AM_ZeroX = 5
AM_AbsY = 6
AM_AbsX = 7
AMX_AbsIndX = 8
AMX_AbsInd = 9
AMX_Relative = 10
AMX_ZeroY = 11
AMX_ZeroIndX = 12
AMX_ZeroInd = 13