;
;	Automatically generated
;
	.include "boot/x16/01constants.inc"
	.include "boot/common/02data.inc"
	.include "boot/common/03stdmac.inc"
	.include "boot/common/boot.asm"
	.include "extern/x16/x16hardware.asm"
	.include "extern/x16/x16print.asm"
	.include "interface/test/iftdummy.asm"
	.include "common/generated/keywords.inc"
	.include "common/math/intmacros.inc"
	.include "common/errors/checksyntax.asm"
	.include "common/errors/errorhandler.asm"
	.include "common/evaluate/binary1.asm"
	.include "common/evaluate/binary2.asm"
	.include "common/evaluate/evaluate.asm"
	.include "common/evaluate/unary.asm"
	.include "common/generated/errors.asm"
	.include "common/generated/keytypes.asm"
	.include "common/generated/vectors.asm"
	.include "common/math/int32binary.asm"
	.include "common/math/int32compare.asm"
	.include "common/math/int32divide.asm"
	.include "common/math/int32fromstr.asm"
	.include "common/math/int32math.asm"
	.include "common/math/int32multiply.asm"
	.include "common/math/int32tostr.asm"
	.include "common/math/int32unary.asm"
	.include "testing/simple/01testing.asm"
	.include "testing/simple/02testcode.asm"
